### ISSUE TITLE
Работы

### ISSUE THREAD

**Issue by ViktorEremin** [ViktorEremin/Unity-2021#1]
Сергей Иванович, проверьте пожалуйста мои работы

**Comment by justjune** [comment]
См. Успеваемость.

**Comment by ViktorEremin** [comment]
Сергей Иванович, загрузил еще пару работ, получилось чуть позже 4 часов

**Comment by justjune** [comment]
См. Успеваемость.

**Comment by ViktorEremin** [comment]
здравствуйте, Сергей Иванович, я подгрузил оставшиеся работы

**Comment by justjune** [comment]
Виктор, здравствуйте! Зачел. Приходите с "хвостовкой".
